[workspace]
members = [
    "sandflow",
    "executor",
    "cluster"
]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "unwind"
rpath = false
