[package]
name = "sandflow"
version = "0.1.0"
authors = ["bmmcq <chenqiang.mcq@gmail.com>"]
edition = "2021"
keywords = ["dataflow", "async", "distributed"]
license = "MIT"

[dependencies]
futures = "0.3"
pin-project-lite = "0.2.8"
sandflow-executor = { path = "../sandflow-executor" }